# general setting
name: fuss_pancreas_dear
backend: dp # DataParallel
type: FussModel
num_gpu: 1
manual_seed: 1234
visualize: True

pose_timestep: 6
pose_milestones:
  2: 2
  4: 4
  6: 6

# path
path:
  resume_state: ~

# datasets
datasets:
  train_dataset:
    name: Train
    type: PairPancreasDataset
    data_root: ./data/pancreas
    phase: train
    return_evecs: True
    return_faces: True
    num_evecs: 40
    start_index: 0
    end_index: 218
    n_combination: 20
  test_dataset:
    name: Test
    type: PairPancreasDataset
    data_root: ./data/pancreas
    phase: test
    return_evecs: True
    return_faces: True
    num_evecs: 40
    start_index: 218
    end_index: 245
  # setting for train dataset
  batch_size: 1
  num_worker: 16

# network setting
networks:
  feature_extractor:
    type: DiffusionNet
    in_channels: 128
    out_channels: 384
    cache_dir: ./pancreas/difussion 
    input_type: wks
  fmap_net:
    type: RegularizedFMNet
    bidirectional: true
  permutation:
    type: Similarity
    tau: 0.07
  interpolator:
    type: ResnetECPos
    c_dim: 3
    dim: 7
    hidden_dim: 128

# training setting
train:
  total_epochs: 10
  optims:
    feature_extractor:
      type: Adam
      lr: 1.0e-3
    interpolator:
      type: Adam
      lr: 1.0e-3
  schedulers:
    feature_extractor:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 10
    interpolator:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 10
  losses:
    surfmnet_loss:
      type: SURFMNetLoss
      w_bij: 1.0
      w_orth: 1.0
      w_lap: 0.0
    couple_loss:
      type: SquaredFrobeniusLoss
      loss_weight: 1.0
    align_loss:
      type: SquaredFrobeniusLoss
      loss_weight: 10.0
    symmetry_loss:
      type: SquaredFrobeniusLoss
      loss_weight: 1.0
    smoothness_loss:
      type: DirichletLoss
      loss_weight: 2.0
    dirichlet_shape_loss:
      type: DirichletLoss
      loss_weight: 1.0e+2
    #chamfer_shape_loss:
    #  type: ChamferLoss
    #  loss_weight: 1.0e+4
    #edge_shape_loss:
    #  type: EdgeLoss
    #  loss_weight: 1.0e+5
    deform_loss:
      type: DeformLoss
      loss_weight: 1.0e+3

# validation setting
val:
  val_freq: 4000
  metrics:
    specificity:
      type: calculate_specificity
    generalization:
      type: calculate_generalization

# log setting
logger:
  print_freq: 20
  save_checkpoint_freq: 5000
